webapp-ZS/Controllers/AdminController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using webapp_ZS.Data;

namespace webapp_ZS.Controllers
{
    [Authorize(Roles = "administrator")]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.UserCount = _context.Users.Count(); 
            ViewBag.CartCount = _context.Carts.Count();
            ViewBag.SalesCount = _context.Sales.Count();
            ViewBag.ArtistCount = _context.Artists.Count();
            ViewBag.ProductCount = _context.Artworks.Count(); 
            return View();
        }
    }
}

webapp-ZS/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webapp_ZS.Data;
using webapp_ZS.Models;

namespace webapp_ZS.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CartsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Carts.Include(c => c.artworks);
            return View(await applicationDbContext.ToListAsync());
        }


        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.artworks)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            ViewData["artworksId"] = new SelectList(_context.Artworks, "artworksId", "artworksName");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,cartPiece,artworksId")] Cart cart)
        {
            ViewData["artworksId"] = new SelectList(_context.Artworks, "artworksId", "artworksName", cart.artworksId);
            cart.cartTime = DateTime.Now;
            Artworks selectedArtwork = await _context.Artworks.FindAsync(cart.artworksId);
            if (selectedArtwork.artworksStockQuantity >= cart.cartPiece)
            {
                // Calculate the total amount based on the artwork's price and sale piece
                cart.cartTotalAmount = selectedArtwork.artworksPrice * cart.cartPiece;
                selectedArtwork.artworksStockQuantity -= cart.cartPiece;
                // total değeri düşür

            }
            else
            {

                return RedirectToAction("Error");

            }
            string? userId = User?.Identity?.Name;
            cart.userIds = userId;

            _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }

            var artwork = await _context.Artworks.FindAsync(cart.artworksId);
            if (artwork == null)
            {
                // Artwork bulunamazsa, bir hata mesajı döndürülebilir.
                return NotFound("Artwork not found");
            }

            // Cart'ın toplam tutarını hesapla
            cart.cartTotalAmount = artwork.artworksPrice * cart.cartPiece;
            string? userId = User?.Identity?.Name;
            cart.userIds = userId;


            ViewData["artworksId"] = new SelectList(_context.Artworks, "artworksId", "artworksName", cart.artworksId);
            return View(cart);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,cartTime,cartPiece,artworksId")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            var artwork = await _context.Artworks.FindAsync(cart.artworksId);
            if (artwork == null)
            {
                // Artwork bulunamazsa, bir hata mesajı döndürülebilir.
                return NotFound("Artwork not found");
            }

            // Cart'ın toplam tutarını hesapla
            cart.cartTotalAmount = artwork.artworksPrice * cart.cartPiece;

            ViewData["artworksId"] = new SelectList(_context.Artworks, "artworksId", "artworksName", cart.artworksId);

            try
            {
                _context.Update(cart);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CartExists(cart.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }


        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.artworks)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Carts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Carts'  is null.");
            }
            var cart = await _context.Carts.FindAsync(id);
            if (cart != null)
            {
                _context.Carts.Remove(cart);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
          return (_context.Carts?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        // GET: Carts/AddSales/5
        public async Task<IActionResult> AddSales(int? id)
        {
            var cart = await _context.Carts
             .FirstOrDefaultAsync(c => c.Id == id);

            if (cart == null)
            {
                return NotFound();
            }
            string? userId = User.Identity?.Name;

            var sale = new Sale
            {
                customerName = "", 
                saleCity = "", 
                saleAdress = "", 
                artworksId = cart.artworksId, 
                cartPiece = cart.cartPiece, 
                cartTotalAmount = (decimal)cart.cartTotalAmount, 
            };

            if (!string.IsNullOrEmpty(userId))
            {
                sale.userIds = userId;
                sale.customerName = userId;
            }


            _context.Sales.Add(sale);
            _context.Carts.Remove(cart);
            await _context.SaveChangesAsync();



            TempData["SuccessMessage"] = "Satış başarıyla oluşturuldu!";
            return RedirectToAction("Edit", "Sales", new { id = sale.Id });
        }


    }
}

webapp-ZS/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webapp_ZS.Data;
using webapp_ZS.Models;

namespace webapp_ZS.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Events.Include(a => a.Artists);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Events/Details/5
        [Authorize(Roles = "administrator")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(a => a.Artists)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        [Authorize(Roles = "administrator")]

        public IActionResult Create()
        {
            ViewData["artistId"] = new SelectList(_context.Artists, "Id", "Id");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]

        public async Task<IActionResult> Create([Bind("Id,eventName,eventTime,eventDescription,artistId")] Event @event)
        {

            _context.Add(@event);
            ViewData["artistId"] = new SelectList(_context.Artists, "Id", "Id", @event.artistId);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));



        }

        // GET: Events/Edit/5
        [Authorize(Roles = "administrator")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["artistId"] = new SelectList(_context.Artists, "Id", "Id", @event.artistId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]

        public async Task<IActionResult> Edit(int id, [Bind("Id,eventName,eventTime,eventDescription,artistId")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }
            ViewData["artistId"] = new SelectList(_context.Artists, "Id", "Id", @event.artistId);


            try
            {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
           
            ViewData["artistId"] = new SelectList(_context.Artists, "Id", "Id", @event.artistId);
        }
        [Authorize(Roles = "administrator")]

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(a => a.Artists)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Events == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Events'  is null.");
            }
            var @event = await _context.Events.FindAsync(id);
            if (@event != null)
            {
                _context.Events.Remove(@event);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return (_context.Events?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

webapp-ZS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webapp_ZS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webapp_ZS.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

    <!-- Custom CSS for additional styling -->
</head>
<body>
    <header>
        <!-- Improved Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sanat Dükkanı</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav mr-auto">
                        @if (User.IsInRole("administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Artists" asp-action="Index">Sanatçılar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Artworks" asp-action="Index">Sanat Eserleri</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Kategoriler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Etkinlikler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Carts" asp-action="Index">Sepet</a>
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Siparişler</a>
                                </li>
                            }
                        </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-4">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <footer class="footer bg-light mt-4 py-3">
        <div class="container text-center">
            &copy; 2023 - Sanat Dükkanı - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>